DROP DATABASE IF EXISTS LORY;
CREATE DATABASE LORY;
USE LORY;
CREATE TABLE Usuario (
idUsuario INT AUTO_INCREMENT UNIQUE NOT NULL,
nomeUsuario VARCHAR(100) NOT NULL,
emailUsuario VARCHAR(100) NOT NULL UNIQUE,
senhaUsuario VARCHAR(100) NOT NULL
);
CREATE TABLE Treino (
id INT AUTO_INCREMENT UNIQUE NOT NULL,
nome VARCHAR(100) NOT NULL,
nivel VARCHAR(20),
dificuldade INT,
musculoTrabalhado VARCHAR(50),
descricao TEXT,
video VARCHAR(255)
);

